// Generated by CoffeeScript 1.3.3
(function() {
  var RedditEngine, reng, root;

  root = window;

  _.templateSettings = {
    interpolate: /\{\{(.+?)\}\}/g
  };

  RedditEngine = (function() {

    function RedditEngine() {}

    RedditEngine.prototype.initialize = function() {
      var pat;
      pat = $("#linktemplate").html();
      console.log(pat);
      this.linktmpl = _.template(pat);
      return console.log("template", this.linktmpl);
    };

    RedditEngine.prototype.fetchLinks = function(cat, qargs) {
      var selector, url,
        _this = this;
      cat = "pics";
      selector = "";
      qargs = qargs = "jsonp=?&";
      url = "http://www.reddit.com/r/" + cat + "/" + selector + ".json?" + qargs + " ";
      console.log("going ajax");
      $.ajax({
        url: url,
        jsonp: "jsonp",
        dataType: "jsonp",
        success: function(resp) {
          var all, d, expanded, it, items, _i, _len;
          items = resp.data.children;
          all = $("<div>");
          root = $("div[data-catname='pics']");
          for (_i = 0, _len = items.length; _i < _len; _i++) {
            it = items[_i];
            d = it.data;
            expanded = _this.linktmpl({
              linkdesc: d.title,
              linkscore: d.score,
              linkimg: d.thumbnail
            });
            console.log(expanded);
            all.append(expanded);
          }
          root.empty();
          root.append(all);
          return console.log(items);
        }
      });
      return "        \n$.getJSON url, (resp) =>\n    items = resp.data.children\n    for it in items\n        console.log it";
    };

    return RedditEngine;

  })();

  root.RedditEngine = RedditEngine;

  reng = null;

  $(function() {
    console.log("starting up");
    root.redditengine = reng = new RedditEngine();
    reng.initialize();
    return reng.fetchLinks("", "");
  });

}).call(this);
